version: '2'
services:
  alice:
    image: trisacrypto/rvasp:alice
    ports:
      - 4435:4434
  bob:
    image: trisacrypto/rvasp:bob
    ports:
      - 4436:4434
  evil:
    image: trisacrypto/rvasp:evil
    ports:
      - 4437:4434
